@baseUrl = http://localhost:3001

### Request 0 : CheckHealth
GET {{baseUrl}}/users/health

### Request 1 : GetUsers
GET {{baseUrl}}/users

### Request 1.1 : GetUsers
GET {{baseUrl}}/users?sortDesc=true

### Request 1.2 : GetUser
GET {{baseUrl}}/users/1


### Request 2 : GetPosts
GET {{baseUrl}}/users/posts

### Request 3 : Error: CreateUser
POST {{baseUrl}}/users/create
content-type: application/json

{
    # "name": "Jhon",
    "email": "jack.jhon@gmail.com"
}

### Request 3.1 : CreateUser
POST {{baseUrl}}/users/create
content-type: application/json

{
    "name": "Jhon",
    "email": "jack.jhon@gmail.com"
}